
package javaapplication1;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;


public class TelaRegistro extends javax.swing.JFrame {

    private static TelaRegistro registro;
    private String Usuario;
    private String Senha;
   
    
    public TelaRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }
    
    public String getUsuario(){
        return this.Usuario;
    }
    
    public String getSenha(){
        return this.Senha;
    }
    
    public static TelaRegistro iniciar(){
        
        
        if(registro==null){
            registro = new TelaRegistro();         
            registro.addWindowListener(new WindowAdapter(){
                @Override
                public void windowClosing(WindowEvent e){                   
                    registro=null;                    
                }                
            });
            return registro;        
        } else
            return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UTFBank = new javax.swing.JLabel();
        txtLogin = new javaapplication1.MyTextField();
        txtSenha2 = new javaapplication1.MyPassword();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenha1 = new javaapplication1.MyPassword();
        cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(11, 35, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 87, 108, 30));

        UTFBank.setBackground(new java.awt.Color(255, 255, 255));
        UTFBank.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        UTFBank.setForeground(new java.awt.Color(255, 255, 255));
        UTFBank.setText("Registro UTFBank");
        jPanel1.add(UTFBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 27, -1, -1));

        txtLogin.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/user.png"))); // NOI18N
        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 117, 242, 34));

        txtSenha2.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/key.png"))); // NOI18N
        txtSenha2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenha2FocusGained(evt);
            }
        });
        jPanel1.add(txtSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 257, 242, 34));

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirme a senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 227, 151, 24));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 157, 108, 24));

        txtSenha1.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/key.png"))); // NOI18N
        txtSenha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenha1FocusGained(evt);
            }
        });
        jPanel1.add(txtSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 187, 242, 34));

        cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        cadastrar.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.setOpaque(false);
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarMouseEntered(evt);
            }
        });
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 131, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        
        Cliente cliente = new Cliente();
        cliente.setLogin(txtLogin.getText());
        cliente.setSenha(txtSenha1.getText());
        cliente.setConfirmaSenha(txtSenha2.getText());
        
        this.Usuario = txtLogin.getText();
        
        if(cliente.getSenha().equals(cliente.getConfirmaSenha())){
            cliente.salvar();
            
            txtLogin.setText("");
            txtSenha1.setText("");
            txtSenha2.setText("");
            //Banco_Frame.play("cadastroSucesso");
            JOptionPane.showMessageDialog(null,"Cadastro Realizado com Sucesso!","Cadastro",JOptionPane.DEFAULT_OPTION);

        }else{
            JOptionPane.showMessageDialog(null,"As senhas não são iguais","Erro",JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_cadastrarActionPerformed

    
    

    
    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        Banco_Frame.play("escrevaLogin");
    }//GEN-LAST:event_txtLoginFocusGained

    private void txtSenha1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha1FocusGained
        Banco_Frame.play("digiteSenha");
    }//GEN-LAST:event_txtSenha1FocusGained

    private void txtSenha2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha2FocusGained
        Banco_Frame.play("confirmeSenha");
    }//GEN-LAST:event_txtSenha2FocusGained

    private void cadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseEntered
        Banco_Frame.play("cadastrar");
    }//GEN-LAST:event_cadastrarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UTFBank;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javaapplication1.MyTextField txtLogin;
    private javaapplication1.MyPassword txtSenha1;
    private javaapplication1.MyPassword txtSenha2;
    // End of variables declaration//GEN-END:variables
}
